### ISSUE TITLE
argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by sbiswanger** [jl94x4/ColleXions#23]
I am running ColleXions in Docker Compose. Version 1.10 did work. Updated docker image, ColleXion stopped working. I downloaded the updated config.json, added my Plex details. When I start the container it successfully connects to Plex, unpins all Collections then throws the following error:

collexions  | 2024-11-30 03:26:03,987 - INFO - Final active special collections: []
collexions  | Traceback (most recent call last):
collexions  |   File "/app/ColleXions.py", line 238, in <module>
collexions  |     main()
collexions  |   File "/app/ColleXions.py", line 225, in main
collexions  |     collections_to_pin = filter_collections(config, all_collections, active_special_collections, collections_to_pin_for_library, library_name)
collexions  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
collexions  |   File "/app/ColleXions.py", line 178, in filter_collections
collexions  |     category_collections = [c for c in all_collections if c.title in collection_names and c.title not in fully_excluded_collections]
collexions  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
collexions  |   File "/app/ColleXions.py", line 178, in <listcomp>
collexions  |     category_collections = [c for c in all_collections if c.title in collection_names and c.title not in fully_excluded_collections]
collexions  |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
collexions  | TypeError: argument of type 'bool' is not iterable

**Comment by jl94x4** [comment]
Can you please supply your config?

**Comment by sbiswanger** [comment]
{
    "plex_url": "http://xxx.xxx.com:32400",
    "plex_token": "xxxxxxxxxxxxxxxxxxxx",
    "library_names": [
        "Movies",
        "TV Shows"
    ],
    "exclusion_list": [
        "Aliens",
        "War Book"
    ],
    "use_inclusion_list": false,
    "include_list": [
        "Inclusion 1",
        "Inclusion 2",
        "Inclusion 3",
        "Inclusion 4",
        "Inclusion 5",
        "Inclusion 6",
        "Inclusion 7",
        "Inlcusion 8"
    ],
    "pinning_interval": 180,
    "number_of_collections_to_pin": {
        "Movies": 3,
        "TV Shows": 1
    },
"categories": {
    "Movies": {
        "always_call": false,
        "Category 1": [
            "Inclusion 1",
            "Inclusion 2"
        ],
        "Category 2": [
            "Inclusion 3",
            "Inclusion 4"
        ]
    },
    "TV Shows": {
        "always_call": false,
        "Category 3": [
            "Inclusion 5",
            "Inclusion 6"
        ],
        "Category 4": [
            "Inclusion 7",
            "Inclusion 8"
        ]
    }
},
    "special_collections": [
        {
            "start_date": "10-01",
            "end_date": "10-31",
            "collection_names": [
                "Halloween Movies"
            ]
        },
        {
            "start_date": "12-02",
            "end_date": "01-03",
            "collection_names": [
                "Christmas Collection"
            ]
        }
    ],
    "discord_webhook_url": "<webhook-url>"
}

**Comment by Aabayoumy** [comment]
I have same issue !

**Comment by jl94x4** [comment]
I have discontinued docker for now, if anyone would like to maintain a docker version please do, and message me too :)
