### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by TechJedi51** [jl94x4/ColleXions#24]
It appears to connect to Plex okay, then unpins some collections, but it never pins anything, nor runs the Discord WH. Could it be something in my config file? 
[config.json](https://github.com/user-attachments/files/17986604/config.json)

`2024-12-02 18:45:11,799 - INFO - Connecting to Plex server...

2024-12-02 18:45:11,817 - INFO - Connected to Plex server successfully.

2024-12-02 18:45:11,819 - INFO - Processing library: Feature Films with 5 collections to pin.

2024-12-02 18:45:11,819 - INFO - Unpinning currently pinned collections...

2024-12-02 18:45:12,013 - INFO - Collection 'Best Films of The Year' unpinned successfully.

2024-12-02 18:45:12,027 - INFO - Collection 'Get Ready-The Sequel is Coming Soon' unpinned successfully.

2024-12-02 18:45:12,040 - INFO - Collection 'Old Movies Just Added' unpinned successfully.

2024-12-02 18:45:12,054 - INFO - Collection 'Trending This Week' unpinned successfully.

2024-12-02 18:45:12,054 - INFO - Skipping unpinning for collection: A Few (in exclusion list)

2024-12-02 18:45:12,096 - INFO - Skipping unpinning for collection: Best of The Past (in exclusion list)

2024-12-02 18:45:12,130 - INFO - Skipping unpinning for collection: Special Collections (in exclusion list)

2024-12-02 18:45:12,176 - INFO - Skipping unpinning for collection: Oscar Collections (in exclusion list)

2024-12-02 18:45:12,190 - INFO - Skipping unpinning for collection: People Collections (in exclusion list)

2024-12-02 18:45:12,221 - INFO - Skipping unpinning for collection: Film Series (in exclusion list)

2024-12-02 18:45:12,647 - INFO - Skipping unpinning for collection: Director's Collections (in exclusion list)

2024-12-02 18:45:12,927 - INFO - Skipping unpinning for collection: Film Formats (in exclusion list)

2024-12-02 18:45:12,944 - INFO - Collection '['Thanksgiving Movies']' is NOT active (standard case).

2024-12-02 18:45:12,944 - INFO - Collection '['Halloween Movies']' is NOT active (standard case).

2024-12-02 18:45:12,945 - INFO - Collection '['Christmas Collection']' is NOT active (cross-year case).

2024-12-02 18:45:12,945 - INFO - Final active special collections: []

Traceback (most recent call last):

  File "/app/ColleXions.py", line 238, in <module>

    main()

  File "/app/ColleXions.py", line 225, in main

    collections_to_pin = filter_collections(config, all_collections, active_special_collections, collections_to_pin_for_library, library_name)

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/ColleXions.py", line 178, in filter_collections

    category_collections = [c for c in all_collections if c.title in collection_names and c.title not in fully_excluded_collections]

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/ColleXions.py", line 178, in <listcomp>

    category_collections = [c for c in all_collections if c.title in collection_names and c.title not in fully_excluded_collections]

                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: argument of type 'bool' is not iterable`

**Comment by jl94x4** [comment]
Is this on docker? Or running via the script manually via python

**Comment by TechJedi51** [comment]
Are there any troubleshooting steps I could try to help resolve the error?

**Comment by Fespinoza831** [comment]
i have the same issue, im running on docker in unraid

**Comment by jl94x4** [comment]
I have discontinues docker for now, you can use the script using python. If anyone would like to maintain a docker version please do, or contact me :)
