### ISSUE TITLE
Parsing dates in special collections is incorrect

### ISSUE THREAD

**Issue by d3mystified** [jl94x4/ColleXions#4]
Example:

```
        {
            "start_date": "2-5",
            "end_date": "2-15",
            "collection_names": [
                "Valentine's Day"
            ]
        },
```

OR

```
        {
            "start_date": "02-05",
            "end_date": "02-15",
            "collection_names": [
                "Valentine's Day"
            ]
        },
```

both result in:

```
Traceback (most recent call last):
  File "/app/ColleXions.py", line 183, in <module>
    main()
  File "/app/ColleXions.py", line 169, in main
    special_collections = get_special_collections(config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ColleXions.py", line 108, in get_special_collections
    start_date = datetime.strptime(special['start_date'], '%Y-%m-%d').date()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2-5' does not match format '%Y-%m-%d'
```

`%Y-%m-%d` seems like the wrong thing to use because the dates will span all years.

**Comment by defluophoenix** [comment]
Are you using the latest version v1.11? The latest version definitely only requires the month and day, the older versions also required year

**Comment by jl94x4** [comment]
This has been fixed in the updated docker.
