### ISSUE TITLE
number_of_collections_to_pin isn't used correctly

### ISSUE THREAD

**Issue by d3mystified** [jl94x4/ColleXions#5]
```
Traceback (most recent call last):
  File "/app/ColleXions.py", line 183, in <module>
    main()
  File "/app/ColleXions.py", line 173, in main
    collections_to_pin = filter_collections(config, all_collections, special_collections)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ColleXions.py", line 149, in filter_collections
    if len(collections_to_pin) < config['number_of_collections_to_pin']:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'dict'
```

You need to do `config['number_of_collections_to_pin'][library_name]`.

Is the author even using this script at all?

**Comment by defluophoenix** [comment]
can you show your config.json? I just ran the script and had no issues

**Comment by jl94x4** [comment]
> I'm using the latest docker image. Seems like it's 10 days old.

Sorry about that, I'll get round to updating it this evening!

**Comment by jl94x4** [comment]
@d3mystified the docker is now up to date
